//
//  IDPRCStyleKit.h
//  ProjectName
//
//  Created by Kaname Noto on 2016/01/20.
//  Copyright (c) 2016 Irimasu Densan Planning. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface IDPRCStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* arrowTargets;

// Colors
+ (UIColor*)arrowColor;

// Generated Images
+ (UIImage*)imageOfArrow;

@end
